### ISSUE TITLE
broken stylesheet?

### ISSUE THREAD

**Issue by zeke** [replicate/llama-chat#18]
Currently seeing this in macOS Chrome at https://llama.replicate.dev

<img width="1552" alt="Screenshot 2023-07-31 at 10 40 04 AM" src="https://github.com/replicate/llama-chat/assets/2289/92006652-b757-4a16-ad57-97476705cb3f">

@replicate/hackers

**Comment by cbh123** [comment]
Fixed! Dropped an import of the stylesheet by accident
