### ISSUE TITLE
Please use a textarea rather than input[type=text] as prompt input

### ISSUE THREAD

**Issue by grayfallstown** [replicate/llama-chat#41]
Using an input all linebreaks are lost. If I copy some text into it and ask llama2 something about that text, all paragraphs are lost, which might change llama2's output.

This is especially problematic when coding with llama2 as an assistant.

**Comment by grayfallstown** [comment]
I just found a [pull request for that](https://github.com/replicate/llama-chat/pull/36)

**Comment by fofr** [comment]
#36 is now merged
